[package]
name = "systoy"
version = "0.0.0"
authors = ["Daniel Harrison <52528+danhhz@users.noreply.github.com>"]
edition = "2018"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
tempfile = "3.2"

[lib]
bench = false

[[bench]]
name = "file"
harness = false
